vich_uploader:
    db_driver: orm

    mappings:
       categories:
           uri_prefix: /uploads/images
           upload_destination: '%kernel.project_dir%/public/uploads/images'
           namer: Vich\UploaderBundle\Naming\PropertyNamer
           inject_on_load: true
           delete_on_update: true
           delete_on_remove: true
